### ISSUE TITLE
pREST support

### ISSUE THREAD

**Issue by avelino** [platformsh/template-builder#315]
What is [pREST](https://github.com/prest/prest): PostgreSQL REST - simplify and accelerate development, instant, realtime, high-performance on any Postgres application, existing or new.

Is an interesting project to develop template builder here or recommends doing in the organization of [pREST](https://github.com/prest/prest).

**Comment by otaviojava** [comment]
Hello Avelino, how are you?
Indeed, you can have this button in your repository.

There is this helpful link where shows the baby-step:
https://platform.sh/deploy/

I've created this sample code where I also have the one-click button:
https://github.com/platformsh-examples/deploy-friday-ep15

Please, let me know if there is any question. I'm glad to help you.
