### ISSUE TITLE
D8 no longer compatible with latest Drush

### ISSUE THREAD

**Issue by gilzow** [platformsh/template-builder#564]
With the release of v11, [Drupal 8 support has been removed from Drush](https://www.drush.org/latest/install/#drupal-compatibility). The D8-based templates currently [require drush with no constraints ](https://github.com/platformsh/template-builder/blob/master/project/drupal.py#L27 )allowing the incompatible version to be installed. This also causes composer to fail due to constraints in dependencies from D8 to conflict with constraints for dependencies from v11 of drush.

Suggestion for fix: add a constraint to drush locking it to v10.

**Comment by chadwcarlson** [comment]
Closes https://github.com/platformsh/template-builder/issues/540
